#!/bin/sh

# Build frontend
cp ~/site_settings/config.beta.js ~/brca-exchange/brca-website/js/config.js
cd ~/brca-exchange/brca-website
npm run build
cd ..

# Deploy backend
cp ~/site_settings/site_settings.beta.py ~/brca-exchange/brca-website/django/brca/site_settings.py
sudo rsync -av --delete ~/brca-exchange/brca-website/django/ /var/www/backend/beta/django
# Fix up ownership. XXX This should be reviewed for security. web2py deployment
# docs suggest this, but it's odd having the app owned by the apache user, since
# file perms then allow writing the application files.
sudo chown -R www-data:www-data /var/www/backend/beta/django

# Not sure this is necessary. Deliver the magic wsgi touch.
sudo touch /var/www/backend/beta/django/wsgi.py

# Deploy the front end
sudo rsync -av --delete ~/brca-exchange/brca-website/build/ /var/www/html/beta


cat > /var/www/html/beta/robots.txt <<EOF
User-agent: *
Disallow: /
EOF
