# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('title', models.TextField(blank=True)),
                ('affiliation', models.TextField(blank=True)),
                ('institution', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('state', models.TextField(blank=True)),
                ('country', models.TextField(blank=True)),
                ('phone_number', models.TextField(blank=True, max_length=30)),
                ('hide_number', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
