# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 11:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160408_1032'),
        ('users', '0005_myuser_email_me'),
    ]

    operations = [
    ]
