# Set up to pass automatically
# Will add unit tests soon
version: 2
jobs:
  test-pipeline:
    working_directory: /pipeline
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo "Tests disabled"
  test-splicing-pipeline:
    working_directory: /splicing-pipeline
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo "Tests disabled"
workflows:
  version: 2
  test-back-end:
    jobs:
      - test-pipeline:
          filters:
            tags:
              only: /.*/
      - test-splicing-pipeline:
          filters:
            tags:
              only: /.*/
