version: 2.1
jobs:
   buildweb:
     circleci_ip_ranges: true
     docker:
       - image: circleci/node:16
       - image: circleci/postgres:9.6.2
         environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: storage.pg
     steps:
       - checkout
       - run:
           name: Setup npm
           working_directory: ~/project/website
           command: npm install
