name: variant_scoring
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - abseil-cpp=20200225.2
  - arrow-cpp=3.0.0
  - backcall=0.2.0
  - brotli=1.0.9
  - bzip2=1.0.8
  - gflags=2.2.2
  - glog=0.4.0
  - glow=1.0.1
  - jedi=0.18.0
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.2.4
  - parso=0.8.2
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - prompt-toolkit=3.0.17
  - pyarrow=3.0.0
  - pygments=2.8.1
  - pyspark=3.1.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=20.0.0
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.35.4
  - statsmodels=0.11.1
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - typish=1.9.2
  - uriparser=0.9.3
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - click==7.1.2
    - CrossMap==0.4.0
    - dill==0.3.3
    - docopt==0.6.2
    - et-xmlfile==1.1.0
    - greenlet==1.0.0
    - intervaltree==3.1.0
    - jdcal==1.4.1
    - multiprocess==0.70.11.1
    - numexpr==2.7.3
    - openpyxl==2.4.11
    - pathos==0.2.7
    - pgpasslib==1.1.0
    - pox==0.2.9
    - ppft==1.6.6.3
    - psycopg2-binary==2.8.6
    - records==0.5.3
    - sortedcontainers==2.3.0
    - sqlalchemy==1.4.12
    - tables==3.6.1
    - tablib==3.0.0
    - toolz==0.11.1
    - hgvs==1.5.2
