#!/bin/bash

echo PATH $PATH
HOST=brcaexchange-deployment1721.cloudapp.net
USER=brca

# directory of this file
DEPLOYMENT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WEBSITE=${DEPLOYMENT}/../website

cd ${WEBSITE}
npm run build:prod

# deploy
rsync -a --delete --rsync-path='sudo rsync' build/ ${USER}@${HOST}:/var/www/html/beta
rsync -a --delete --rsync-path='sudo rsync' django/ ${USER}@${HOST}:/var/www/backend/beta/django

ssh -l${USER} ${HOST} 'cp ~/site_settings/config.beta.js /var/www/html/beta/config.js'
ssh -l${USER} ${HOST} 'cp ~/site_settings/site_settings.beta.py /var/www/backend/beta/django/brca/site_settings.py'
ssh -l${USER} ${HOST} 'touch /var/www/backend/beta/django/wsgi.py'
