#!/bin/sh

SRC=beta
DST=production
HTML=/var/www/html
BACKEND=/var/www/backend

rsync -a --delete ${HTML}/${SRC}/ ${HTML}/${DST}
rsync -a --delete ${BACKEND}/${SRC}/django/ ${BACKEND}/${DST}/django

cp ~/site_settings/config.${DST}.js /var/www/html/${DST}/config.js
cp ~/site_settings/site_settings.${DST}.py /var/www/backend/${DST}/django/brca/site_settings.py

. /var/www/backend/${SRC}/virtualenv/bin/activate
requirements=$(pip freeze)
deactivate
requirements=$(echo ${requirements}) # drop carriage returns
. /var/www/backend/${DST}/virtualenv/bin/activate
pip install ${requirements}
sudo apache2ctl restart
