#!/bin/sh
set -x
set -o nounset
set -o errexit

HOST=${HOST:-brcaexchange.org}
USER=brca

ssh -l${USER} ${HOST} <<-'ENDSSH'
    set -x
    #set -o nounset # 'activate' accesses unbound vars
    set -o errexit
    SRC=beta
    DST=production
    HTML=/var/www/html
    BACKEND=/var/www/backend

    rsync -a --delete ${HTML}/${SRC}/ ${HTML}/${DST}
    rsync -a --delete --exclude="/uploads" --exclude="/downloads/*" ${BACKEND}/${SRC}/django/ ${BACKEND}/${DST}/django

    cp ~/site_settings/config.${DST}.js /var/www/html/${DST}/config.js
    cp ~/site_settings/site_settings.${DST}.py /var/www/backend/${DST}/django/brca/site_settings.py

    . /var/www/backend/${SRC}/virtualenv/bin/activate
    requirements=$(pip3 freeze)
    deactivate
    requirements=$(echo ${requirements}) # drop carriage returns
    . /var/www/backend/${DST}/virtualenv/bin/activate
    pip3 install ${requirements}
    python3 /var/www/backend/production/django/manage.py migrate --noinput --verbosity 2
    sudo apache2ctl restart
ENDSSH
