table brcaExchanges
" bed9 + many additional fields from brcaExchange.org "
    (
    string chrom;      "Chromosome (or contig, scaffold, etc.)"
    uint   chromStart; "Start position in chromosome"
    uint   chromEnd;   "End position in chromosome"
    string name;       "Name of item"
    uint   score;      "Score from 0-1000"
    char[1] strand;    "+ or -"
    uint thickStart;   "Start of where display should be thick (start codon)"
    uint thickEnd;     "End of where display should be thick (stop codon)"
    uint reserved;     "Used as itemRgb as of 2004-11-22"
    string outLink;     "Link to BRCAExchange.org"
    lstring Source; "Source"
    lstring Ref; "Ref"
    lstring Alt; "Alt"
    lstring URL_ENIGMA; "URL ENIGMA"
    lstring Condition_ID_type_ENIGMA; "Condition ID type ENIGMA"
    lstring Condition_ID_value_ENIGMA; "Condition ID value ENIGMA"
    lstring Condition_category_ENIGMA; "Condition category ENIGMA"
    lstring Clinical_significance_ENIGMA; "Clinical significance ENIGMA"
    lstring Date_last_evaluated_ENIGMA; "Date last evaluated ENIGMA"
    lstring Assertion_method_ENIGMA; "Assertion method ENIGMA"
    lstring Assertion_method_citation_ENIGMA; "Assertion method citation ENIGMA"
    lstring Clinical_significance_citations_ENIGMA; "Clinical significance citations ENIGMA"
    lstring Comment_on_clinical_significance_ENIGMA; "Comment on clinical significance ENIGMA"
    lstring Collection_method_ENIGMA; "Collection method ENIGMA"
    lstring Allele_origin_ENIGMA; "Allele origin ENIGMA"
    lstring ClinVarAccession_ENIGMA; "ClinVarAccession ENIGMA"
    lstring Clinical_Significance_ClinVar; "Clinical Significance ClinVar"
    lstring Date_Last_Updated_ClinVar; "Date Last Updated ClinVar"
    lstring Submitter_ClinVar; "Submitter ClinVar"
    lstring SCV_ClinVar; "SCV ClinVar"
    lstring Allele_Origin_ClinVar; "Allele Origin ClinVar"
    lstring Method_ClinVar; "Method ClinVar"
    lstring Variant_frequency_LOVD; "Variant frequency LOVD"
    lstring Minor_allele_frequency_ESP; "Minor allele frequency ESP"
    lstring EUR_Allele_frequency_1000_Genomes; "EUR Allele frequency 1000 Genomes"
    lstring AFR_Allele_frequency_1000_Genomes; "AFR Allele frequency 1000 Genomes"
    lstring AMR_Allele_frequency_1000_Genomes; "AMR Allele frequency 1000 Genomes"
    lstring EAS_Allele_frequency_1000_Genomes; "EAS Allele frequency 1000 Genomes"
    lstring Allele_frequency_1000_Genomes; "Allele frequency 1000 Genomes"
    lstring SAS_Allele_frequency_1000_Genomes; "SAS Allele frequency 1000 Genomes"
    lstring Allele_frequency_ExAC; "Allele frequency ExAC"
    lstring Patient_nationality_BIC; "Patient nationality BIC"
    lstring Clinical_importance_BIC; "Clinical importance BIC"
    lstring Clinical_classification_BIC; "Clinical classification BIC"
    lstring Literature_citation_BIC; "Literature citation BIC"
    lstring Number_of_family_member_carrying_mutation_BIC; "Number of family member carrying mutation BIC"
    lstring Germline_or_Somatic_BIC; "Germline or Somatic BIC"
    lstring Ethnicity_BIC; "Ethnicity BIC"
    lstring Mutation_type_BIC; "Mutation type BIC"
    lstring IARC_class_exLOVD; "IARC class exLOVD"
    lstring Sum_family_LR_exLOVD; "Sum family LR exLOVD"
    lstring Combined_prior_probablility_exLOVD; "Combined prior probablility exLOVD"
    lstring Literature_source_exLOVD; "Literature source exLOVD"
    lstring Co_occurrence_LR_exLOVD; "Co occurrence LR exLOVD"
    lstring Posterior_probability_exLOVD; "Posterior probability exLOVD"
    lstring Missense_analysis_prior_probability_exLOVD; "Missense analysis prior probability exLOVD"
    lstring Segregation_LR_exLOVD; "Segregation LR exLOVD"
    lstring Polyphen_Prediction; "Polyphen Prediction"
    lstring Polyphen_Score; "Polyphen Score"
    lstring Sift_Score; "Sift Score"
    lstring Sift_Prediction; "Sift Prediction"
    lstring Reference_Sequence; "Reference Sequence"
    lstring BIC_Nomenclature; "BIC Nomenclature"
    lstring HGVS_cDNA; "HGVS cDNA"
    lstring Gene_Symbol; "Gene Symbol"
    lstring HGVS_Protein; "HGVS Protein"
    lstring Protein_Change; "Protein Change"
    lstring Genomic_Coordinate_hg38; "Genomic Coordinate hg38"
    lstring Hg38_Start; "Hg38 Start"
    lstring Hg38_End; "Hg38 End"
    lstring Hg37_Start; "Hg37 Start"
    lstring Hg37_End; "Hg37 End"
    lstring Hg36_Start; "Hg36 Start"
    lstring Hg36_End; "Hg36 End"
    lstring HGVS_RNA; "HGVS RNA"
    lstring Allele_Frequency; "Allele Frequency"
    lstring Max_Allele_Frequency; "Max Allele Frequency"
    lstring Genomic_Coordinate_hg37; "Genomic Coordinate hg37"
    lstring Genomic_Coordinate_hg36; "Genomic Coordinate hg36"
    lstring Source_URL; "Source URL"
    lstring Discordant; "Discordant"
    lstring Synonyms; "Synonyms"
    lstring Pathogenicity_expert; "Pathogenicity expert"
    lstring Pathogenicity_all; "Pathogenicity all"
    lstring pyhgvs_Genomic_Coordinate_36; "pyhgvs Genomic Coordinate 36"
    lstring pyhgvs_Genomic_Coordinate_37; "pyhgvs Genomic Coordinate 37"
    lstring pyhgvs_Genomic_Coordinate_38; "pyhgvs Genomic Coordinate 38"
    lstring pyhgvs_Hg36_Start; "pyhgvs Hg36 Start"
    lstring pyhgvs_Hg36_End; "pyhgvs Hg36 End"
    lstring pyhgvs_cDNA; "pyhgvs cDNA"
    lstring pyhgvs_Protein; "pyhgvs Protein"
    lstring change_type; "change type"
    string _mouseOver; "mouse over field hidden"
    )