# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_autocomplete_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='Hg36_End',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variant',
            name='Hg36_Start',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variant',
            name='Hg37_End',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variant',
            name='Hg37_Start',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variant',
            name='Hg38_End',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variant',
            name='Hg38_Start',
            field=models.IntegerField(default=1),
        ),
    ]
