# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_autocomplete_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='Hg36_End',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Hg36_Start',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Hg37_End',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Hg37_Start',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Hg38_End',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Hg38_Start',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
