# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0004_autocomplete_words'),
    ]

    operations = [
        migrations.RunSQL("""CREATE MATERIALIZED VIEW currentvariant AS ( 
            SELECT * FROM "variant" WHERE (
                "id" IN ( SELECT DISTINCT ON ("Genomic_Coordinate_hg38") "id" FROM "variant" ORDER BY "Genomic_Coordinate_hg38" ASC, "Data_Release_id" DESC )
            )
        );"""),
    ]
