# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def create_initial_data_release(apps, schema_editor):
    DataRelease = apps.get_model('data', 'DataRelease')
    Variant = apps.get_model('data', 'Variant')
    initial_release = DataRelease(comment="initial variant set", variants_added = Variant.objects.count())
    initial_release.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_autocomplete_words.py'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('variants_added', models.IntegerField(default=0)),
                ('variants_modified', models.IntegerField(default=0)),
                ('variants_deleted', models.IntegerField(default=0)),
                ('columns_added', models.TextField(null=True)),
                ('columns_deleted', models.TextField(null=True)),
            ],
            options={
                'db_table': 'data_release',
            },
        ),
        migrations.RunPython(create_initial_data_release)
    ]
