# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 16:41
from __future__ import unicode_literals

from django.db import migrations


# NOTE: This migration was written specifically to address text changes in
# release notes pertaining to releases on 11-5-16 and 10-6-16.
class Migration(migrations.Migration):
    dependencies = [
        ('data', '0005_create_materialized_view'),
    ]

    operations = [
        # Reformat link to git commit for v1 data
        migrations.RunSQL(
            """
                UPDATE data_release SET notes = replace(notes, 'https://github.com/BD2KGenomics/brca-exchange/tree/master/pipeline/luigi commit ID f8e675e2459df4c22694184ee0daf0af9a0bfe64', 'https://github.com/BD2KGenomics/brca-exchange/tree/f8e675e2459df4c22694184ee0daf0af9a0bfe64/pipeline/luigi);'
            """
        ),

        # Reformat link to git commit for v2 data
        migrations.RunSQL(
            """
                UPDATE data_release SET notes = replace(notes, 'https://github.com/BD2KGenomics/brca-exchange/tree/master/pipeline/luigi, commit ID 59929a3b13e0ed412c64edd1631dc9d826ee0dd0', 'https://github.com/BD2KGenomics/brca-exchange/tree/59929a3b13e0ed412c64edd1631dc9d826ee0dd0/pipeline/luigi);'
            """
        ),

        # Remove old link to known issues
        migrations.RunSQL(
            """
                UPDATE data_release SET notes = regexp_replace(notes, '\r\n\r\n\r\nKnown issues:  For the current list, see https://docs.google.com/document/d/1PQdYreWFKYiumR0R_4B__FRjFMMO-yuZlcoDIHpStCg/edit.', '', 'g');
            """
        ),
    ]
