# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_versioned_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='Data_Release',
            # Get data_release_id_seq.start_value instead of assuming 1 ?
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.DataRelease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Variant_Deletion',
            field=models.BooleanField(default=False),
        ),
    ]
