# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_versioned_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarelease',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
