# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_update_enigma_format_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarelease',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
