# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_change_type_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='Variant_Deletion',
        ),
        migrations.AddField(
            model_name='variant',
            name='Change_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.ChangeType'),
            preserve_default=False,
        ),
    ]
