# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-10 10:08


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Variant'),
        ),
    ]
