# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20161007_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarelease',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
