# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20161007_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='BIC_Identifier',
            new_name='BIC_Nomenclature',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='Pathogenicity_research',
            new_name='Pathogenicity_all',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='Pathogenicity_default',
            new_name='Pathogenicity_expert',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='Origin_of_variant_LOVD',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='PolyPhen_VEP',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='SIFT_VEP',
        ),
        migrations.AddField(
            model_name='variant',
            name='Alt',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Chr',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Polyphen_Prediction',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Polyphen_Score',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Pos',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Ref',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Sift_Prediction',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='Sift_Score',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
