# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_update_search_index_and_autocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Description_ClinVar',
            field=models.TextField(default=b'-'),
        ),
    ]
