# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-18 03:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_add_report_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='DateSignificanceLastEvaluated_ClinVar',
            field=models.TextField(default=b'-'),
        ),
        migrations.AddField(
            model_name='report',
            name='SCV_Version_ClinVar',
            field=models.TextField(default=b'-'),
        ),
        migrations.AddField(
            model_name='variant',
            name='DateSignificanceLastEvaluated_ClinVar',
            field=models.TextField(default=b'-'),
        ),
        migrations.AddField(
            model_name='variant',
            name='SCV_Version_ClinVar',
            field=models.TextField(default=b'-'),
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW IF EXISTS currentvariant;
            CREATE MATERIALIZED VIEW currentvariant AS (
                SELECT * FROM "variant" WHERE (
                    "id" IN ( SELECT DISTINCT ON ("Genomic_Coordinate_hg38") "id" FROM "variant" ORDER BY "Genomic_Coordinate_hg38" ASC, "Data_Release_id" DESC )
                )
            );
            """
        ),
    ]
