# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-07 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_report_synonyms_clinvar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('journal', models.TextField()),
                ('url', models.TextField()),
                ('keywords', models.TextField()),
                ('abstract', models.TextField()),
                ('year', models.IntegerField()),
                ('pmid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VariantPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentions', models.TextField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Paper')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Variant')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='variants',
            field=models.ManyToManyField(through='data.VariantPaper', to='data.Variant'),
        ),
    ]
