# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-08-29 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_auto_20180827_0640'),
        ('data', '0033_report_synonyms_clinvar'),
    ]

    operations = [
    ]
