# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-04 05:52


from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.fields import ArrayField


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_add_submission_id_lovd_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('journal', models.TextField()),
                ('url', models.TextField()),
                ('keywords', models.TextField()),
                ('abstract', models.TextField()),
                ('year', models.IntegerField()),
                ('pmid', models.IntegerField()),
                ('deleted', models.BooleanField())
            ],
        ),
        migrations.CreateModel(
            name='VariantPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_hg38', models.TextField()),
                ('mentions', ArrayField(models.TextField())),
                ('deleted', models.BooleanField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Paper')),
            ],
        ),
    ]
