# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-27 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_add_findlay_ring_function_scores'),
        ('data', '0038_report_variant_new_indices'),
    ]

    operations = [
    ]
