# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-26 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_variantpaper_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='crawl_date',
            field=models.DateTimeField(null=True),
        ),
    ]
