# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-18 16:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_paper_crawl_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantRepresentation',
            fields=[
                ('Variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Variant')),
                ('Description', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
