# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-02 01:07
from __future__ import unicode_literals

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_add_gnomad_fields'),
    ]

    operations = [
        RunSQL("""
        create index report_Source_ClinVar on report ("Source", "SCV_ClinVar");
        create index report_Source_LOVD on report ("Source", "Submission_ID_LOVD");
        """, reverse_sql="""
        drop index report_Source_ClinVar;
        drop index report_Source_LOVD;
        """)
    ]
