# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-29 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_add_gnomad_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='Genomic_Coordinate_hg36',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='Hg36_End',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='Hg36_Start',
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW IF EXISTS currentvariant;
            CREATE MATERIALIZED VIEW currentvariant AS (
                SELECT * FROM "variant" WHERE (
                    "id" IN ( SELECT DISTINCT ON ("Genomic_Coordinate_hg38") "id" FROM "variant" ORDER BY "Genomic_Coordinate_hg38" ASC, "Data_Release_id" DESC )
                )
            );
            """
        )
    ]
