import click
import pandas as pd

from common import vcf_files_helper

HGVS_38_COL = 'pyhgvs_Genomic_Coordinate_38'
VCF_INFO_COL = 7
VARS_OF_INTEREST = ["BayesDel_nsfp33a_noAF"]


def _read_part(path):
    try:
        return vcf_files_helper.read_vcf_as_dataframe(path)
    except pd.errors.EmptyDataError:
        return pd.DataFrame()


def victor_results_as_df(path):
    """
    Reading a VCF generated by the VICTOR pipeline and extracting useful information
    (e.g. bayesdel scores) out of the VCF Info field.

    :param path: path to VCF file annotated by VICTOR
    :return: dataframe with one column per variable of interest + join key
    """
    victor_vcf_df = _read_part(path)

    # Drop extraneous columns after VCF column 7, which should be the real end of the VCF.  This is done because
    # certain Victor output files contain extraneous VCF columns (11/22/25)
    victor_vcf_df = victor_vcf_df.iloc[:, :VCF_INFO_COL+1]

    # processing VCF INFO col, generate a dict variable_name -> value out of the info field for every record
    info_dict = victor_vcf_df.iloc[:, VCF_INFO_COL].str.split(';').apply(
        lambda l: {s.split('=')[0]: '='.join(s.split('=')[1:]) for s in l})

    return pd.DataFrame.from_records(info_dict.values, index=info_dict.index)[VARS_OF_INTEREST + [HGVS_38_COL]]


@click.command()
@click.argument('victor_file', nargs=1, type=click.Path(readable=True))
@click.option('--built-tsv', required=True, type=click.Path(readable=True))
@click.option('--output', required=True, type=click.Path(writable=True))
def main(victor_file, built_tsv, output):
    df_victor = victor_results_as_df(victor_file)
    df = pd.read_csv(built_tsv, sep='\t', keep_default_na=False)

    df.merge(df_victor, on=HGVS_38_COL, how='left').to_csv(output, sep='\t', index=False, na_rep='-')


if __name__ == "__main__":
    main()
