import click
import pandas as pd

from common import vcf_files_helper
from common.hgvs_utils import HgvsWrapper

coord_col = 'genomics_coord'
VCF_INFO_COL = 7
VARS_OF_INTEREST = ["BayesDel_nsfp33a_noAF"]


def _read_part(path):
    try:
        return vcf_files_helper.read_vcf_as_dataframe(path)
    except pd.errors.EmptyDataError:
        return pd.DataFrame()


def victor_results_as_df(path):
    """
    Reading a VCF generated by the VICTOR pipeline and extracting useful information
    (e.g. bayesdel scores) out of the VCF Info field.

    :param path: path to VCF file annotated by VICTOR
    :return: dataframe with one column per variable of interest + join key
    """
    victor_vcf_df = _read_part(path)

    # Drop extraneous columns after VCF column 7, which should be the real end of the VCF.  This is done because
    # certain Victor output files contain extraneous VCF columns (11/22/25)
    victor_vcf_df = victor_vcf_df.iloc[:, :VCF_INFO_COL+1]

    # processing VCF INFO col, generate a dict variable_name -> value out of the info field for every record
    info_dict = victor_vcf_df.iloc[:, VCF_INFO_COL].str.split(';').apply(
        lambda l: {s.split('=')[0]: '='.join(s.split('=')[1:]) for s in l})

    # generating dataframe out of dict, one column per variable
    df_victor_props = pd.DataFrame.from_records(info_dict.values, index=info_dict.index)[VARS_OF_INTEREST]

    # join back to vcf dataframe
    df_ret = victor_vcf_df.merge(df_victor_props, how='inner', left_index=True, right_index=True)

    # calculate a coordinate representation to join with built_tsv
    hgvs_proc = HgvsWrapper.get_instance()
    df_ret[coord_col] = df_ret.apply(
        lambda row: hgvs_proc.genomic_hgvs(str(row.iloc[0]), row.iloc[1], row.iloc[3], row.iloc[4]),
        axis=1
    )

    # dropping VCF columns, leaving columns for variable of interest + join field
    return df_ret.drop(columns=[c for c in range(0, VCF_INFO_COL + 1)])


@click.command()
@click.argument('victor_file', nargs=1, type=click.Path(readable=True))
@click.option('--built-tsv', required=True, type=click.Path(readable=True))
@click.option('--output', required=True, type=click.Path(writable=True))
def main(victor_file, built_tsv, output):
    df_victor = victor_results_as_df(victor_file)
    df = pd.read_csv(built_tsv, sep='\t', keep_default_na=False)

    hgvs_proc = HgvsWrapper.get_instance()
    df[coord_col] = df.apply(
        lambda row: hgvs_proc.genomic_hgvs(str(row['Chr']), int(row['Pos']), row['Ref'], row['Alt']),
        axis=1
    )
    df.merge(df_victor, on=coord_col, how='left') \
      .drop(columns=[coord_col]) \
      .to_csv(output, sep='\t', index=False, na_rep='-')


if __name__ == "__main__":
    main()
