#!/usr/bin/env python2.7

"""
Charles Markello
5/22/2015

Description:
	Python script 'bic2vcf' takes in a bic table flat file and converts it to
	vcf format. Used primarily for the purposes of data extraction for integration
	into the ga4gh reference server.
"""


from __future__ import print_function, division
import argparse
import sys
import os
import collections
import pyhgvs as hgvs
import pyhgvs.utils as hgvs_utils
from pygr.seqdb import SequenceFileDB


def parse_args():
	"""
	Description:
		function 'parse_args' parses arguments from command-line and returns an argparse
		object containing the arguments and their values. Default values are 'False' if option
		is not listed in the command, else the option value is set to True.
	"""
	parser = argparse.ArgumentParser(description='Convert UMD database table to VCF format.')
	parser.add_argument('-i', '--inBIC', type=argparse.FileType('r'),
		help='Input BIC file for conversion.')
	parser.add_argument('-a', '--inAnnot', type=argparse.FileType('r'),
		help='Input BIC annotation file for conversion. Tab-delimited with 1st column representing\n\
		field name and 2nd column representing the field description.')
	parser.add_argument('-o', '--out', type=argparse.FileType('w'),
		help='Ouput VCF file result.')
	parser.add_argument('-b', '--brca', type=int,
		help='BRCA gene which BIC variant table was derrived from. (1 for BRCA1 or 2 for BRCA2).')
	parser.add_argument('-g', '--gpath', default='/hive/groups/cgl/brca/phase1/data/resources/hg19.fa',
		help='Whole path to genome file. Default: (/hive/groups/cgl/brca/phase1/data/resources/hg19.fa)')
	parser.add_argument('-r', '--rpath', default='/hive/groups/cgl/brca/phase1/data/resources/refseq_annotation.hg19.psl',
		help='Whole path to refSeq file. Default: (/hive/groups/cgl/brca/phase1/data/resources/refseq_annotation.hg19.psl)')

	options = parser.parse_args()
	return options

def main(args):
	options = parse_args()
	bicFile = options.inBIC
	annotFile = options.inAnnot
	vcfFile = options.out
	brcaGene = options.brca
	genome_path = options.gpath
	refseq_path = options.rpath

	with open(refseq_path) as infile:
		transcripts = hgvs_utils.read_transcripts(infile)

	genome = SequenceFileDB(genome_path)

	def get_transcript(name):
		return transcripts.get(name)

	# open and store annotation fields in a dictionary
	annotDict = defaultdict()
	for line in annotFile:
		line = line.strip().split('\t')
		annotDict[line[0]] = line[1]

	print('##fileformat=VCFv4.0', file=vcfFile)
	print('##source=BIC', file=vcfFile)
	print('##reference=GRCh37', file=vcfFile)

	headerline = bicFile.readline().strip().split('\t')

	for field in headerline:
		print(field)


if __name__ == "__main__":
	sys.exit(main(sys.argv))




