# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:57
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=512)),
                ('genomic_coordinate', models.CharField(max_length=512)),
                ('reference_sequence', models.CharField(max_length=512)),
                ('hgvs_cdna', models.CharField(max_length=512)),
                ('bic_nomenclature', models.CharField(max_length=512)),
                ('abbrev_aa_change', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('condition_id_type', models.CharField(max_length=512)),
                ('condition_id_value', models.CharField(max_length=512)),
                ('condition_category', models.CharField(max_length=512)),
                ('clinical_significance', models.CharField(max_length=512)),
                ('date_last_evaluated', models.CharField(max_length=512)),
                ('assertion_method', models.CharField(max_length=512)),
                ('assertion_method_citation', models.CharField(max_length=512)),
                ('clinical_significance_citations', models.CharField(max_length=512)),
                ('comment_on_clinical_significance', models.CharField(max_length=512)),
                ('collection_method', models.CharField(max_length=512)),
                ('allele_origin', models.CharField(max_length=512)),
                ('clinvaraccession', models.CharField(max_length=512)),
                ('hgvs_protein', models.CharField(max_length=512)),
            ],
            managers=[
                ('objects', data.models.VariantManager()),
            ],
        ),
    ]
