# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 16:52
from __future__ import unicode_literals

import csv
import os.path

from django.conf import settings
from django.db import migrations

from ..models import Variant


def load_from_tsv(apps, schema_editor):
    file = os.path.join(settings.BASE_DIR, 'data', 'resources', 'variants.tsv')
    print(file)
    with open(file) as tsv:
        for row in csv.reader(tsv, dialect="excel-tab"):
            Variant.objects.create_variant(row)


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_from_tsv),
    ]
