# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-12 18:17


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_update_search_index_for_MAF_ESP_rename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Minor_allele_frequency_ESP_percent',
            new_name='Minor_allele_frequency_percent_ESP',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='Minor_allele_frequency_ESP_percent',
            new_name='Minor_allele_frequency_percent_ESP',
        ),
    ]
