# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-22 16:01


import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_report_change_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDiff',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Report')),
                ('report_diff', data.models.LegacyJSONField()),
            ],
        ),
    ]
