# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-11 07:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_paper_variantpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='SCV_ClinVar',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Submission_ID_LOVD',
            field=models.TextField(db_index=True, default=b'-'),
        ),
        migrations.AlterIndexTogether(
            name='report',
            index_together=set([('Data_Release', 'Submission_ID_LOVD'), ('Data_Release', 'SCV_ClinVar')]),
        ),
        migrations.RunSQL("""
        create index variant_hg38_hash_idx on variant using hash ("Genomic_Coordinate_hg38")
        """, reverse_sql="""
        drop index if exists variant_hg38_hash_idx
        """)
    ]
