# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-12-06 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_add_genomic_hgvs_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Classification_LOVD',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='Remarks_LOVD',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='Classification_LOVD',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='Remarks_LOVD',
            field=models.TextField(null=True),
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW IF EXISTS currentvariant;
            CREATE MATERIALIZED VIEW currentvariant AS (
                SELECT * FROM "variant" WHERE (
                    "id" IN ( SELECT DISTINCT ON ("Genomic_Coordinate_hg38") "id" FROM "variant" ORDER BY "Genomic_Coordinate_hg38" ASC, "Data_Release_id" DESC )
                )
            );
            """
        ),
    ]
