# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-09-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_add_enigma_brca12_functional_assays_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Class_Fernandes_ENIGMA_BRCA12_Functional_Assays',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Discordant_Ikegami_ENIGMA_BRCA12_Functional_Assays',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='Class_Fernandes_ENIGMA_BRCA12_Functional_Assays',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='Discordant_Ikegami_ENIGMA_BRCA12_Functional_Assays',
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW IF EXISTS currentvariant;
            CREATE MATERIALIZED VIEW currentvariant AS (
                SELECT * FROM "variant" WHERE (
                    "id" IN ( SELECT DISTINCT ON ("Genomic_Coordinate_hg38") "id" FROM "variant" ORDER BY "Genomic_Coordinate_hg38" ASC, "Data_Release_id" DESC )
                )
            );
            """
        )
    ]
