# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-04-21 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_add_splice_ai_fields_and_update_empties'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='Provisional_Evidence_Code_Bioinfo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='variant',
            name='Provisional_Evidence_Code_Popfreq',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='variant',
            name='Provisional_Evidence_Description_Bioinfo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='variant',
            name='Provisional_Evidence_Description_Popfreq',
            field=models.TextField(default=''),
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW IF EXISTS currentvariant;
            CREATE MATERIALIZED VIEW currentvariant AS (
                SELECT * FROM "variant" WHERE (
                    "id" IN ( SELECT DISTINCT ON ("Genomic_Coordinate_hg38") "id" FROM "variant" ORDER BY "Genomic_Coordinate_hg38" ASC, "Data_Release_id" DESC )
                )
            );
            """
        )
    ]
