# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
