# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_me',
            field=models.BooleanField(default=True),
        ),
    ]
