# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 12:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='key_expires',
        ),
    ]
