# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 17:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160420_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
            ],
        ),
    ]
