# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160805_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='email_me',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='include_me',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
