# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160807_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='longitude',
            field=models.TextField(blank=True),
        ),
    ]
