# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveUser',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Users Awaiting Email Confirmation',
            },
            bases=('users.myuser',),
        ),
        migrations.CreateModel(
            name='ProxyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'All Users',
            },
            bases=('users.myuser',),
        ),
        migrations.CreateModel(
            name='UnapprovedUser',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Users Awaiting Approval',
            },
            bases=('users.myuser',),
        ),
        migrations.AddField(
            model_name='myuser',
            name='admin_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
