# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 14:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_admin_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['lastName', 'firstName']},
        ),
    ]
