# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 15:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160912_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inactiveuser',
            options={'verbose_name': 'inactive user', 'verbose_name_plural': 'Users Awaiting Email Confirmation'},
        ),
        migrations.AlterModelOptions(
            name='proxyuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'All Users'},
        ),
        migrations.AlterModelOptions(
            name='unapproveduser',
            options={'verbose_name': 'unapproved user', 'verbose_name_plural': 'Users Awaiting Approval'},
        ),
    ]
